config/routes.rb
Rails.application.routes.draw do
  resources :todos, except: %i[show]
  root 'todos#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/assignee.rb
class Assignee < ApplicationRecord
  scope :for_todo_list,
        ->(todo_list) {
          return none if todo_list.nil?
          return where(name: %w[John Michael James Robert]) if todo_list.name == 'Todo list 1'
          return where(name: %w[Sara Mary Patricia Jeniffer]) if todo_list.name == 'Todo list 2'
          all
        }
end

app/models/todo.rb
class Todo < ApplicationRecord
  belongs_to :todo_list, required: false
  belongs_to :assignee, required: false

  scope :completed, -> { where.not(completed_at: nil) }
  scope :not_completed, -> { where(completed_at: nil) }

  def completed?
    completed_at.present?
  end

  def completed=(value)
    self.completed_at = value ? Time.now : nil
  end
end

app/models/todo_list.rb
class TodoList < ApplicationRecord
  has_many :todos
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, only: %i[edit update destroy]

  before_action only: %i[index] do
    redirect_to todos_path(state: 'all') unless params.key?(:state)
  end

  # GET /todos or /todos.json
  def index
    @todos = Todo.preload(:todo_list)
    @sort_direction = params.fetch(:filters, {}).fetch(:sort_direction, 'asc')
    @todo_counts = { all: @todos.count, active: @todos.not_completed.count, completed: @todos.completed.count }

    @todos = @todos.order(description: @sort_direction)
    @todos = @todos.not_completed if params[:state] == 'active'
    @todos = @todos.completed if params[:state] == 'completed'
  end

  # GET /todos/new
  def new
    @todo = Todo.new
    @todo_lists = TodoList.order(:name)

    todo_list_id = params.fetch(:todo, {}).fetch(:todo_list_id, @todo.todo_list_id)
    @assignees = Assignee.order(:name).for_todo_list(@todo_lists.find_by(id: todo_list_id))
  end

  # GET /todos/1/edit
  def edit
    @todo_lists = TodoList.order(:name)

    todo_list_id = params.fetch(:todo, {}).fetch(:todo_list_id, @todo.todo_list_id)
    @assignees = Assignee.order(:name).for_todo_list(@todo_lists.find_by(id: todo_list_id))
  end

  # POST /todos or /todos.json
  def create
    @todo = Todo.new(todo_params)

    if @todo.save
      redirect_to todos_url, notice: 'Todo was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /todos/1 or /todos/1.json
  def update
    if @todo.update(todo_params)
      redirect_to todos_url, notice: 'Todo was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /todos/1 or /todos/1.json
  def destroy
    @todo.destroy

    respond_to do |format|
      format.html { redirect_to todos_url, notice: 'Todo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_todo
    @todo = Todo.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def todo_params
    params.require(:todo).permit(:description, :todo_list_id, :assignee_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Stimulus Reflex Demo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application/bundle", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application/bundle", "data-turbo-track": "reload", defer: true %>
  </head>

  <body class="bg-slate-100 text-sm">
    <div id="notifications" class="fixed top-0 left-0 right-0 flex flex-col gap-2 items-center p-4 pointer-events-none" data-controller="notifications">
      <template data-notifications-target="template">
        <div class="bg-rose-500 p-3 rounded text-white shadow-lg pointer-events-auto" data-controller="notification" style="display: none">
          {{message}}
          <button class="text-rose-100 cursor-pointer hover:bg-white rounded-sm hover:text-rose-500 w-5 h-5 ml-5 inline-flex items-center justify-center" data-action="click->notification#close">⛌</button>
        </div>
      </template>
    </div>
    <header class="bg-white border-b py-4 px-8 flex gap-8 items-center">
      <a class="font-bold text-lg" href="<%= root_url %>">Stimulus Reflex Demo</a>
      <%= link_to 'Todos', todos_path, class: 'text-blue-500 hover:underline' %>
    </header>
    <main class="p-8">
      <%= yield %>
    </main>
  </body>
</html>

app/views/shared/_saved_at.html.erb
<div class="bg-gray-100 rounded-sm px-3 py-2">
  Saved at <%= l(model.updated_at, format: '%H:%M:%S') %> (<%= time_ago_in_words(model.updated_at) %> ago)
</div>

app/views/todos/_form.html.erb
<% data = { reflex_serialize_form: 'true' } %>
<% data = data.merge({ reflex: 'change->TodosReflex#save', sgid: todo.to_sgid.to_s }) unless todo.new_record? %>

<%= form_with(model: todo, html: { class: 'flex flex-col gap-4', data: data }) do |form| %>
  <% if todo.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(todo.errors.count, "error") %> prohibited this todo from being saved:</h2>

      <ul>
        <% todo.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <% unless todo.new_record? %>
    <div id="<%= dom_id(todo, :saved_at) %>">
      <%= render('shared/saved_at', model: todo) %>
    </div>
  <% end %>

  <div class="flex flex-col gap-2">
    <%= form.label :description, class: 'block font-semibold' %>
    <%= form.text_field :description, autofocus: true %>
  </div>

  <div class="flex flex-col gap-2">
    <%= form.label :todo_list_id, class: 'block font-semibold' %>
    <% data = { reflex: 'change', reflex_serialize_form: 'true' } %>
    <%= form.collection_select :todo_list_id, @todo_lists, :id, :name, { include_blank: true }, { data: data } %>
  </div>

  <% if @assignees.present? %>
    <div class="flex flex-col gap-2">
      <%= form.label :assignee_id, class: 'block font-semibold' %>
      <div class="flex gap-2 items-center"><%= form.collection_radio_buttons :assignee_id, @assignees, :id, :name, { include_blank: 'Select...' } %></div>
    </div>
  <% end %>

  <div class="py-2">
    <hr />
  </div>

  <div>
    <%= form.submit(class: 'bg-green-500 text-white rounded px-3 py-2 cursor-pointer') %>
  </div>
<% end %>

app/views/todos/_tabs.html.erb
<div class="flex">
    <% %w[all active completed].each do |state| %>
      <%= link_to "#{state.humanize} (#{counts.fetch(state.to_sym)})", todos_path(state: state), class: ['px-4 py-2', ('bg-blue-500 text-white' if state == params[:state])] %>
    <% end %>
  </div>

app/views/todos/_todo.html.erb
<tr id="<%= dom_id(todo) %>">
  <td class="border-b p-2" width="1%">
    <%= fields_for(todo) do |f| %>
      <%= f.check_box :completed?, { data: { reflex: 'change->TodosReflex#toggle', sgid: todo.to_sgid.to_s } } %>
    <% end %>
  </td>
  <td class="border-b p-2">
    <%= link_to todo.description, edit_todo_path(todo), class: ['text-blue-500 hover:underline', ('line-through text-gray-500' if todo.completed?)] %>
  </td>
  <td class="border-b p-2">
    <%= tag.span(todo.todo_list.name, class: ('line-through text-gray-500' if todo.completed?)) if todo.todo_list.present? %>
  </td>
  <td class="border-b p-2">
    <%= tag.span(todo.assignee.name, class: ('line-through text-gray-500' if todo.completed?)) if todo.assignee.present? %>
  </td>
</tr>

app/views/todos/edit.html.erb
<header class="flex items-baseline gap-4">
  <%= link_to "Todos", todos_path, class: 'text-blue-500 hover:underline text-base' %>
  <span>»</span>
  <h1 class="text-base font-bold">Editing todo</h1>
</header>

<div class="mt-4 p-6 bg-white border rounded">
  <%= render "form", todo: @todo %>
</div>

app/views/todos/index.html.erb
<header class="flex justify-between items-baseline gap-4">
  <h1 class="text-base font-bold">Todos</h1>
  <%= link_to "+ New todo", new_todo_path, class: 'text-base text-blue-500 hover:underline' %>
</header>

<div class="bg-white border rounded-md shadow-sm mt-6 p-6">
  <%= render 'tabs', counts: @todo_counts %>

  <div class="mt-4">
    <%= form_for(:filters) do |form| %>
      <% sort_directions = [['Ascending', 'asc'], ['Descending', 'desc']] %>
      <% data = { reflex: 'change->TodosReflex#apply_filter', reflex_serialize_form: 'true' } %>
      <%= form.select(:sort_direction, sort_directions, { selected: @sort_direction }, { data: data }) %>
    <% end %>
  </div>

  <% if @todos.any? %>
    <table class="w-full border-collapse mt-4">
      <thead class="text-left bg-gray-100">
        <th class="border-b p-2"></th>
        <th class="border-b p-2">Description</th>
        <th class="border-b p-2">Todo list</th>
        <th class="border-b p-2">Assignee</th>
      </thead>
      <tbody>
        <%= render @todos %>
      </tbody>
    </table>
  <% else %>
    <p class="text-gray-700 mt-6">No results found</p>
  <% end %>
</div>

app/views/todos/new.html.erb
<header class="flex items-baseline gap-4">
  <%= link_to "Todos", todos_path, class: 'text-blue-500 hover:underline text-base' %>
  <span>»</span>
  <h1 class="text-base font-bold">New todo</h1>
</header>

<div class="bg-white border rounded-md shadow-sm mt-6 p-6">
  <%= render "form", todo: @todo %>
</div>